# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from kocheng/decode_status.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class decode_status(genpy.Message):
  _md5sum = "a2ff2b7cd0443eeeee765956b8e698bf"
  _type = "kocheng/decode_status"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 run_course_status
int32 heartbeat_status
int32 follow_status
int32 docking_status
"""
  __slots__ = ['run_course_status','heartbeat_status','follow_status','docking_status']
  _slot_types = ['int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       run_course_status,heartbeat_status,follow_status,docking_status

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(decode_status, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.run_course_status is None:
        self.run_course_status = 0
      if self.heartbeat_status is None:
        self.heartbeat_status = 0
      if self.follow_status is None:
        self.follow_status = 0
      if self.docking_status is None:
        self.docking_status = 0
    else:
      self.run_course_status = 0
      self.heartbeat_status = 0
      self.follow_status = 0
      self.docking_status = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4i().pack(_x.run_course_status, _x.heartbeat_status, _x.follow_status, _x.docking_status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.run_course_status, _x.heartbeat_status, _x.follow_status, _x.docking_status,) = _get_struct_4i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4i().pack(_x.run_course_status, _x.heartbeat_status, _x.follow_status, _x.docking_status))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.run_course_status, _x.heartbeat_status, _x.follow_status, _x.docking_status,) = _get_struct_4i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4i = None
def _get_struct_4i():
    global _struct_4i
    if _struct_4i is None:
        _struct_4i = struct.Struct("<4i")
    return _struct_4i
