// Generated by gencpp from file roboboat/flight_mode.msg
// DO NOT EDIT!


#ifndef ROBOBOAT_MESSAGE_FLIGHT_MODE_H
#define ROBOBOAT_MESSAGE_FLIGHT_MODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboboat
{
template <class ContainerAllocator>
struct flight_mode_
{
  typedef flight_mode_<ContainerAllocator> Type;

  flight_mode_()
    : flight_mode()  {
    }
  flight_mode_(const ContainerAllocator& _alloc)
    : flight_mode(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _flight_mode_type;
  _flight_mode_type flight_mode;





  typedef boost::shared_ptr< ::roboboat::flight_mode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboboat::flight_mode_<ContainerAllocator> const> ConstPtr;

}; // struct flight_mode_

typedef ::roboboat::flight_mode_<std::allocator<void> > flight_mode;

typedef boost::shared_ptr< ::roboboat::flight_mode > flight_modePtr;
typedef boost::shared_ptr< ::roboboat::flight_mode const> flight_modeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboboat::flight_mode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboboat::flight_mode_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboboat

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geographic_msgs': ['/opt/ros/kinetic/share/geographic_msgs/cmake/../msg'], 'roboboat': ['/home/amvui/AUVSI/src/roboboat/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'mavros_msgs': ['/opt/ros/kinetic/share/mavros_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'uuid_msgs': ['/opt/ros/kinetic/share/uuid_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboboat::flight_mode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboboat::flight_mode_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboboat::flight_mode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboboat::flight_mode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboboat::flight_mode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboboat::flight_mode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboboat::flight_mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ec7751446dccbf592ba3e57dd292976";
  }

  static const char* value(const ::roboboat::flight_mode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ec7751446dccbf5ULL;
  static const uint64_t static_value2 = 0x92ba3e57dd292976ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboboat::flight_mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboboat/flight_mode";
  }

  static const char* value(const ::roboboat::flight_mode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboboat::flight_mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string flight_mode\n\
";
  }

  static const char* value(const ::roboboat::flight_mode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboboat::flight_mode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.flight_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct flight_mode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboboat::flight_mode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboboat::flight_mode_<ContainerAllocator>& v)
  {
    s << indent << "flight_mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.flight_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOBOAT_MESSAGE_FLIGHT_MODE_H
