// Generated by gencpp from file roboboat/setpoint.msg
// DO NOT EDIT!


#ifndef ROBOBOAT_MESSAGE_SETPOINT_H
#define ROBOBOAT_MESSAGE_SETPOINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace roboboat
{
template <class ContainerAllocator>
struct setpoint_
{
  typedef setpoint_<ContainerAllocator> Type;

  setpoint_()
    : setpoint(0)  {
    }
  setpoint_(const ContainerAllocator& _alloc)
    : setpoint(0)  {
  (void)_alloc;
    }



   typedef int16_t _setpoint_type;
  _setpoint_type setpoint;





  typedef boost::shared_ptr< ::roboboat::setpoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::roboboat::setpoint_<ContainerAllocator> const> ConstPtr;

}; // struct setpoint_

typedef ::roboboat::setpoint_<std::allocator<void> > setpoint;

typedef boost::shared_ptr< ::roboboat::setpoint > setpointPtr;
typedef boost::shared_ptr< ::roboboat::setpoint const> setpointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::roboboat::setpoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::roboboat::setpoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace roboboat

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geographic_msgs': ['/opt/ros/kinetic/share/geographic_msgs/cmake/../msg'], 'roboboat': ['/home/amvui/AUVSI/src/roboboat/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'mavros_msgs': ['/opt/ros/kinetic/share/mavros_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'uuid_msgs': ['/opt/ros/kinetic/share/uuid_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::roboboat::setpoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::roboboat::setpoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboboat::setpoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::roboboat::setpoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboboat::setpoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::roboboat::setpoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::roboboat::setpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ee399a1f7e5b4decdfc42e0ba4ab098";
  }

  static const char* value(const ::roboboat::setpoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ee399a1f7e5b4deULL;
  static const uint64_t static_value2 = 0xcdfc42e0ba4ab098ULL;
};

template<class ContainerAllocator>
struct DataType< ::roboboat::setpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "roboboat/setpoint";
  }

  static const char* value(const ::roboboat::setpoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::roboboat::setpoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 setpoint\n\
";
  }

  static const char* value(const ::roboboat::setpoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::roboboat::setpoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.setpoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setpoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::roboboat::setpoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::roboboat::setpoint_<ContainerAllocator>& v)
  {
    s << indent << "setpoint: ";
    Printer<int16_t>::stream(s, indent + "  ", v.setpoint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOBOAT_MESSAGE_SETPOINT_H
