// Generated by gencpp from file kocheng/debug_mission.msg
// DO NOT EDIT!


#ifndef KOCHENG_MESSAGE_DEBUG_MISSION_H
#define KOCHENG_MESSAGE_DEBUG_MISSION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kocheng
{
template <class ContainerAllocator>
struct debug_mission_
{
  typedef debug_mission_<ContainerAllocator> Type;

  debug_mission_()
    : setpoint(0)
    , state(0)
    , effort(0)
    , longitude(0.0)
    , latitude(0.0)  {
    }
  debug_mission_(const ContainerAllocator& _alloc)
    : setpoint(0)
    , state(0)
    , effort(0)
    , longitude(0.0)
    , latitude(0.0)  {
  (void)_alloc;
    }



   typedef int16_t _setpoint_type;
  _setpoint_type setpoint;

   typedef int16_t _state_type;
  _state_type state;

   typedef int16_t _effort_type;
  _effort_type effort;

   typedef float _longitude_type;
  _longitude_type longitude;

   typedef float _latitude_type;
  _latitude_type latitude;





  typedef boost::shared_ptr< ::kocheng::debug_mission_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kocheng::debug_mission_<ContainerAllocator> const> ConstPtr;

}; // struct debug_mission_

typedef ::kocheng::debug_mission_<std::allocator<void> > debug_mission;

typedef boost::shared_ptr< ::kocheng::debug_mission > debug_missionPtr;
typedef boost::shared_ptr< ::kocheng::debug_mission const> debug_missionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kocheng::debug_mission_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kocheng::debug_mission_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kocheng

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geographic_msgs': ['/opt/ros/kinetic/share/geographic_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'mavros_msgs': ['/opt/ros/kinetic/share/mavros_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'kocheng': ['/home/amvui/AUVSI/src/kocheng/msg'], 'uuid_msgs': ['/opt/ros/kinetic/share/uuid_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kocheng::debug_mission_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kocheng::debug_mission_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kocheng::debug_mission_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kocheng::debug_mission_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kocheng::debug_mission_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kocheng::debug_mission_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kocheng::debug_mission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ca02c94f587bbdb18e5bb5621c35260";
  }

  static const char* value(const ::kocheng::debug_mission_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ca02c94f587bbdbULL;
  static const uint64_t static_value2 = 0x18e5bb5621c35260ULL;
};

template<class ContainerAllocator>
struct DataType< ::kocheng::debug_mission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kocheng/debug_mission";
  }

  static const char* value(const ::kocheng::debug_mission_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kocheng::debug_mission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 setpoint\n\
int16 state\n\
int16 effort\n\
float32 longitude\n\
float32 latitude\n\
";
  }

  static const char* value(const ::kocheng::debug_mission_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kocheng::debug_mission_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.setpoint);
      stream.next(m.state);
      stream.next(m.effort);
      stream.next(m.longitude);
      stream.next(m.latitude);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct debug_mission_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kocheng::debug_mission_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kocheng::debug_mission_<ContainerAllocator>& v)
  {
    s << indent << "setpoint: ";
    Printer<int16_t>::stream(s, indent + "  ", v.setpoint);
    s << indent << "state: ";
    Printer<int16_t>::stream(s, indent + "  ", v.state);
    s << indent << "effort: ";
    Printer<int16_t>::stream(s, indent + "  ", v.effort);
    s << indent << "longitude: ";
    Printer<float>::stream(s, indent + "  ", v.longitude);
    s << indent << "latitude: ";
    Printer<float>::stream(s, indent + "  ", v.latitude);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KOCHENG_MESSAGE_DEBUG_MISSION_H
