// Generated by gencpp from file kocheng/decode_status.msg
// DO NOT EDIT!


#ifndef KOCHENG_MESSAGE_DECODE_STATUS_H
#define KOCHENG_MESSAGE_DECODE_STATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kocheng
{
template <class ContainerAllocator>
struct decode_status_
{
  typedef decode_status_<ContainerAllocator> Type;

  decode_status_()
    : run_course_status(0)
    , heartbeat_status(0)
    , follow_status(0)
    , docking_status(0)
    , flag_status(0)  {
    }
  decode_status_(const ContainerAllocator& _alloc)
    : run_course_status(0)
    , heartbeat_status(0)
    , follow_status(0)
    , docking_status(0)
    , flag_status(0)  {
  (void)_alloc;
    }



   typedef int32_t _run_course_status_type;
  _run_course_status_type run_course_status;

   typedef int32_t _heartbeat_status_type;
  _heartbeat_status_type heartbeat_status;

   typedef int32_t _follow_status_type;
  _follow_status_type follow_status;

   typedef int32_t _docking_status_type;
  _docking_status_type docking_status;

   typedef int32_t _flag_status_type;
  _flag_status_type flag_status;





  typedef boost::shared_ptr< ::kocheng::decode_status_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kocheng::decode_status_<ContainerAllocator> const> ConstPtr;

}; // struct decode_status_

typedef ::kocheng::decode_status_<std::allocator<void> > decode_status;

typedef boost::shared_ptr< ::kocheng::decode_status > decode_statusPtr;
typedef boost::shared_ptr< ::kocheng::decode_status const> decode_statusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kocheng::decode_status_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kocheng::decode_status_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kocheng

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geographic_msgs': ['/opt/ros/kinetic/share/geographic_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'mavros_msgs': ['/opt/ros/kinetic/share/mavros_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'kocheng': ['/home/mfikih15/Documents/AUVSI/src/kocheng/msg'], 'uuid_msgs': ['/opt/ros/kinetic/share/uuid_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kocheng::decode_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kocheng::decode_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kocheng::decode_status_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kocheng::decode_status_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kocheng::decode_status_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kocheng::decode_status_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kocheng::decode_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39541b4d1e52937d3a67a84020aded6d";
  }

  static const char* value(const ::kocheng::decode_status_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39541b4d1e52937dULL;
  static const uint64_t static_value2 = 0x3a67a84020aded6dULL;
};

template<class ContainerAllocator>
struct DataType< ::kocheng::decode_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kocheng/decode_status";
  }

  static const char* value(const ::kocheng::decode_status_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kocheng::decode_status_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 run_course_status\n\
int32 heartbeat_status\n\
int32 follow_status\n\
int32 docking_status\n\
int32 flag_status\n\
";
  }

  static const char* value(const ::kocheng::decode_status_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kocheng::decode_status_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.run_course_status);
      stream.next(m.heartbeat_status);
      stream.next(m.follow_status);
      stream.next(m.docking_status);
      stream.next(m.flag_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct decode_status_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kocheng::decode_status_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kocheng::decode_status_<ContainerAllocator>& v)
  {
    s << indent << "run_course_status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.run_course_status);
    s << indent << "heartbeat_status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.heartbeat_status);
    s << indent << "follow_status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.follow_status);
    s << indent << "docking_status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.docking_status);
    s << indent << "flag_status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.flag_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KOCHENG_MESSAGE_DECODE_STATUS_H
