// Generated by gencpp from file kocheng/image_out.msg
// DO NOT EDIT!


#ifndef KOCHENG_MESSAGE_IMAGE_OUT_H
#define KOCHENG_MESSAGE_IMAGE_OUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kocheng
{
template <class ContainerAllocator>
struct image_out_
{
  typedef image_out_<ContainerAllocator> Type;

  image_out_()
    : state_x(0)
    , state_y(0)
    , count(0)  {
    }
  image_out_(const ContainerAllocator& _alloc)
    : state_x(0)
    , state_y(0)
    , count(0)  {
  (void)_alloc;
    }



   typedef int32_t _state_x_type;
  _state_x_type state_x;

   typedef int32_t _state_y_type;
  _state_y_type state_y;

   typedef int32_t _count_type;
  _count_type count;





  typedef boost::shared_ptr< ::kocheng::image_out_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kocheng::image_out_<ContainerAllocator> const> ConstPtr;

}; // struct image_out_

typedef ::kocheng::image_out_<std::allocator<void> > image_out;

typedef boost::shared_ptr< ::kocheng::image_out > image_outPtr;
typedef boost::shared_ptr< ::kocheng::image_out const> image_outConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kocheng::image_out_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kocheng::image_out_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kocheng

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geographic_msgs': ['/opt/ros/kinetic/share/geographic_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'mavros_msgs': ['/opt/ros/kinetic/share/mavros_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'kocheng': ['/home/mfikih15/Documents/AUVSI/src/kocheng/msg'], 'uuid_msgs': ['/opt/ros/kinetic/share/uuid_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kocheng::image_out_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kocheng::image_out_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kocheng::image_out_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kocheng::image_out_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kocheng::image_out_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kocheng::image_out_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kocheng::image_out_<ContainerAllocator> >
{
  static const char* value()
  {
    return "46ace0b0293b73ffe37427e1226523ef";
  }

  static const char* value(const ::kocheng::image_out_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x46ace0b0293b73ffULL;
  static const uint64_t static_value2 = 0xe37427e1226523efULL;
};

template<class ContainerAllocator>
struct DataType< ::kocheng::image_out_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kocheng/image_out";
  }

  static const char* value(const ::kocheng::image_out_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kocheng::image_out_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 state_x\n\
int32 state_y\n\
int32 count\n\
";
  }

  static const char* value(const ::kocheng::image_out_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kocheng::image_out_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state_x);
      stream.next(m.state_y);
      stream.next(m.count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct image_out_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kocheng::image_out_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kocheng::image_out_<ContainerAllocator>& v)
  {
    s << indent << "state_x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.state_x);
    s << indent << "state_y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.state_y);
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KOCHENG_MESSAGE_IMAGE_OUT_H
