// Generated by gencpp from file kocheng/mission.msg
// DO NOT EDIT!


#ifndef KOCHENG_MESSAGE_MISSION_H
#define KOCHENG_MESSAGE_MISSION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kocheng
{
template <class ContainerAllocator>
struct mission_
{
  typedef mission_<ContainerAllocator> Type;

  mission_()
    : navigation_status(false)
    , go_to_speed_status(false)
    , speed_status(false)  {
    }
  mission_(const ContainerAllocator& _alloc)
    : navigation_status(false)
    , go_to_speed_status(false)
    , speed_status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _navigation_status_type;
  _navigation_status_type navigation_status;

   typedef uint8_t _go_to_speed_status_type;
  _go_to_speed_status_type go_to_speed_status;

   typedef uint8_t _speed_status_type;
  _speed_status_type speed_status;





  typedef boost::shared_ptr< ::kocheng::mission_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kocheng::mission_<ContainerAllocator> const> ConstPtr;

}; // struct mission_

typedef ::kocheng::mission_<std::allocator<void> > mission;

typedef boost::shared_ptr< ::kocheng::mission > missionPtr;
typedef boost::shared_ptr< ::kocheng::mission const> missionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kocheng::mission_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kocheng::mission_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kocheng

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geographic_msgs': ['/opt/ros/kinetic/share/geographic_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'mavros_msgs': ['/opt/ros/kinetic/share/mavros_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'kocheng': ['/home/amvui/AUVSI/src/kocheng/msg'], 'uuid_msgs': ['/opt/ros/kinetic/share/uuid_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kocheng::mission_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kocheng::mission_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kocheng::mission_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kocheng::mission_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kocheng::mission_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kocheng::mission_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kocheng::mission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2ed7d7d69b51a422c56195bb0025beea";
  }

  static const char* value(const ::kocheng::mission_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2ed7d7d69b51a422ULL;
  static const uint64_t static_value2 = 0xc56195bb0025beeaULL;
};

template<class ContainerAllocator>
struct DataType< ::kocheng::mission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kocheng/mission";
  }

  static const char* value(const ::kocheng::mission_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kocheng::mission_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool navigation_status\n\
bool go_to_speed_status\n\
bool speed_status\n\
";
  }

  static const char* value(const ::kocheng::mission_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kocheng::mission_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.navigation_status);
      stream.next(m.go_to_speed_status);
      stream.next(m.speed_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct mission_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kocheng::mission_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kocheng::mission_<ContainerAllocator>& v)
  {
    s << indent << "navigation_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.navigation_status);
    s << indent << "go_to_speed_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.go_to_speed_status);
    s << indent << "speed_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.speed_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KOCHENG_MESSAGE_MISSION_H
