// Generated by gencpp from file kocheng/nav_msgs.msg
// DO NOT EDIT!


#ifndef KOCHENG_MESSAGE_NAV_MSGS_H
#define KOCHENG_MESSAGE_NAV_MSGS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kocheng
{
template <class ContainerAllocator>
struct nav_msgs_
{
  typedef nav_msgs_<ContainerAllocator> Type;

  nav_msgs_()
    : setpoint(0)
    , state(0)
    , effort(0)  {
    }
  nav_msgs_(const ContainerAllocator& _alloc)
    : setpoint(0)
    , state(0)
    , effort(0)  {
  (void)_alloc;
    }



   typedef int16_t _setpoint_type;
  _setpoint_type setpoint;

   typedef int16_t _state_type;
  _state_type state;

   typedef int16_t _effort_type;
  _effort_type effort;





  typedef boost::shared_ptr< ::kocheng::nav_msgs_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kocheng::nav_msgs_<ContainerAllocator> const> ConstPtr;

}; // struct nav_msgs_

typedef ::kocheng::nav_msgs_<std::allocator<void> > nav_msgs;

typedef boost::shared_ptr< ::kocheng::nav_msgs > nav_msgsPtr;
typedef boost::shared_ptr< ::kocheng::nav_msgs const> nav_msgsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kocheng::nav_msgs_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kocheng::nav_msgs_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace kocheng

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'geographic_msgs': ['/opt/ros/kinetic/share/geographic_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'mavros_msgs': ['/opt/ros/kinetic/share/mavros_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'kocheng': ['/home/amvui/AUVSI/src/kocheng/msg'], 'uuid_msgs': ['/opt/ros/kinetic/share/uuid_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::kocheng::nav_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kocheng::nav_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kocheng::nav_msgs_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kocheng::nav_msgs_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kocheng::nav_msgs_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kocheng::nav_msgs_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kocheng::nav_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ea1d017b4a253e899268e6002fac34d";
  }

  static const char* value(const ::kocheng::nav_msgs_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ea1d017b4a253e8ULL;
  static const uint64_t static_value2 = 0x99268e6002fac34dULL;
};

template<class ContainerAllocator>
struct DataType< ::kocheng::nav_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kocheng/nav_msgs";
  }

  static const char* value(const ::kocheng::nav_msgs_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kocheng::nav_msgs_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 setpoint\n\
int16 state\n\
int16 effort\n\
";
  }

  static const char* value(const ::kocheng::nav_msgs_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kocheng::nav_msgs_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.setpoint);
      stream.next(m.state);
      stream.next(m.effort);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct nav_msgs_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kocheng::nav_msgs_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kocheng::nav_msgs_<ContainerAllocator>& v)
  {
    s << indent << "setpoint: ";
    Printer<int16_t>::stream(s, indent + "  ", v.setpoint);
    s << indent << "state: ";
    Printer<int16_t>::stream(s, indent + "  ", v.state);
    s << indent << "effort: ";
    Printer<int16_t>::stream(s, indent + "  ", v.effort);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KOCHENG_MESSAGE_NAV_MSGS_H
